# Site settings
title: ShiningBridge
email: shiningbridge@github.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: /camBlog   # "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: zcambridge
github_username:  shiningbridge

# Build settings
markdown: redcarpet  
# highlighter: rouge
encoding: utf-8
permalink: /:year/:month/:day/:title
#safe: true
#lsi: false